### ISSUE TITLE
Incompatible with Python2.6- or Jython

### ISSUE THREAD

**Issue by VVasyaev** [adriank/ObjectPath#51]
The library failing with the following error:

**AttributeError: 'tuple' object has no attribute 'major'**

**Comment by adriank** [comment]
Py 2.6 and Jython are generally unsupported. If you'd like to add support for them, feel free to PR them.

**Comment by VVasyaev** [comment]
i did! you'd merged the fix few minutes ago :)

**Comment by adriank** [comment]
This is not the only thing that doesn't work in 2.6... :)

**Comment by VVasyaev** [comment]
I'm using your library (btw, thank a lot for it!) in the Robot Framework which is running from Jython (due to environment) so i had to fix this attribute error to have ability at least do not have issues at the start moment
